# Generated by Django 4.2.7 on 2025-10-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chapters', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.CharField(help_text="e.g., '2024-06' for June 2024", max_length=7)),
                ('slip_audit_file', models.CharField(blank=True, max_length=255)),
                ('member_names_file', models.CharField(blank=True, max_length=255, null=True)),
                ('referral_matrix_data', models.JSONField(blank=True, default=dict)),
                ('oto_matrix_data', models.JSONField(blank=True, default=dict)),
                ('combination_matrix_data', models.JSONField(blank=True, default=dict)),
                ('tyfcb_inside_data', models.JSONField(blank=True, default=dict)),
                ('tyfcb_outside_data', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='chapters.chapter')),
            ],
            options={
                'db_table': 'chapters_monthlyreport',
                'ordering': ['-month_year'],
                'unique_together': {('chapter', 'month_year')},
            },
        ),
        migrations.CreateModel(
            name='MemberMonthlyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrals_given', models.IntegerField(default=0)),
                ('referrals_received', models.IntegerField(default=0)),
                ('one_to_ones_completed', models.IntegerField(default=0)),
                ('tyfcb_inside_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tyfcb_outside_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('missing_otos', models.JSONField(blank=True, default=list, help_text="Member IDs they haven't done OTOs with")),
                ('missing_referrals_given_to', models.JSONField(blank=True, default=list, help_text="Member IDs they haven't given referrals to")),
                ('missing_referrals_received_from', models.JSONField(blank=True, default=list, help_text="Member IDs they haven't received referrals from")),
                ('priority_connections', models.JSONField(blank=True, default=list, help_text='Members appearing in multiple missing lists')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_stats', to='members.member')),
                ('monthly_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_stats', to='reports.monthlyreport')),
            ],
            options={
                'db_table': 'chapters_membermonthlystats',
                'ordering': ['member__first_name'],
                'unique_together': {('member', 'monthly_report')},
            },
        ),
    ]
