# Generated by Django 4.2.7 on 2025-10-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyreport',
            name='member_names_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='slip_audit_file',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
