# Generated by Django 4.2.7 on 2025-08-25 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("location", models.CharField(max_length=200)),
                ("meeting_day", models.CharField(blank=True, max_length=20)),
                ("meeting_time", models.TimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("normalized_name", models.CharField(db_index=True, max_length=100)),
                ("business_name", models.CharField(blank=True, max_length=200)),
                ("classification", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("is_active", models.BooleanField(default=True)),
                ("joined_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="chapters.chapter",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["first_name", "last_name"],
                "unique_together": {("chapter", "normalized_name")},
            },
        ),
        migrations.CreateModel(
            name="MonthlyChapterReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "report_month",
                    models.DateField(
                        help_text="First day of the month (e.g., 2024-12-01)"
                    ),
                ),
                ("total_referrals_given", models.IntegerField(default=0)),
                ("total_referrals_received", models.IntegerField(default=0)),
                ("total_one_to_ones", models.IntegerField(default=0)),
                (
                    "total_tyfcb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("active_member_count", models.IntegerField(default=0)),
                ("avg_referrals_per_member", models.FloatField(default=0)),
                ("avg_one_to_ones_per_member", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_reports",
                        to="chapters.chapter",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_month"],
                "unique_together": {("chapter", "report_month")},
            },
        ),
        migrations.CreateModel(
            name="MemberMonthlyMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_month", models.DateField()),
                ("referrals_given", models.IntegerField(default=0)),
                ("referrals_received", models.IntegerField(default=0)),
                ("one_to_ones_completed", models.IntegerField(default=0)),
                (
                    "tyfcb_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("performance_score", models.FloatField(default=0)),
                (
                    "total_possible_otos",
                    models.IntegerField(
                        default=0, help_text="Based on chapter member count"
                    ),
                ),
                (
                    "oto_completion_rate",
                    models.FloatField(
                        default=0, help_text="Percentage of possible OTOs completed"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "chapter_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="member_metrics",
                        to="chapters.monthlychapterreport",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_metrics",
                        to="chapters.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-report_month", "member__first_name"],
                "unique_together": {("member", "report_month")},
            },
        ),
    ]
