# Generated by Django 4.2.7 on 2025-10-01 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TYFCB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('currency', models.CharField(default='AED', max_length=3)),
                ('within_chapter', models.BooleanField(default=True)),
                ('date_closed', models.DateField(auto_now_add=True)),
                ('week_of', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyfcbs_given', to='members.member')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tyfcbs_received', to='members.member')),
            ],
            options={
                'verbose_name': 'TYFCB',
                'verbose_name_plural': 'TYFCBs',
                'db_table': 'analytics_tyfcb',
                'ordering': ['-date_closed'],
            },
        ),
        migrations.CreateModel(
            name='OneToOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(auto_now_add=True)),
                ('week_of', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('member1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_ones_as_member1', to='members.member')),
                ('member2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='one_to_ones_as_member2', to='members.member')),
            ],
            options={
                'verbose_name': 'One-to-One Meeting',
                'verbose_name_plural': 'One-to-One Meetings',
                'db_table': 'analytics_onetoone',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_given', models.DateField(auto_now_add=True)),
                ('week_of', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_given', to='members.member')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_received', to='members.member')),
            ],
            options={
                'db_table': 'analytics_referral',
                'ordering': ['-date_given'],
                'unique_together': {('giver', 'receiver', 'date_given')},
            },
        ),
    ]
