# Generated by Django 4.2.7 on 2025-08-25 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chapters", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TYFCB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("within_chapter", models.BooleanField(default=True)),
                ("date_closed", models.DateField(auto_now_add=True)),
                ("week_of", models.DateField(blank=True, null=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "giver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tyfcbs_given",
                        to="chapters.member",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tyfcbs_received",
                        to="chapters.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "TYFCB",
                "verbose_name_plural": "TYFCBs",
                "ordering": ["-date_closed"],
            },
        ),
        migrations.CreateModel(
            name="OneToOne",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meeting_date", models.DateField(auto_now_add=True)),
                ("week_of", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=200)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "member1",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_to_ones_as_member1",
                        to="chapters.member",
                    ),
                ),
                (
                    "member2",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_to_ones_as_member2",
                        to="chapters.member",
                    ),
                ),
            ],
            options={
                "verbose_name": "One-to-One Meeting",
                "verbose_name_plural": "One-to-One Meetings",
                "ordering": ["-meeting_date"],
            },
        ),
        migrations.CreateModel(
            name="DataImportSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("file_size", models.PositiveIntegerField()),
                ("import_date", models.DateTimeField(auto_now_add=True)),
                ("records_processed", models.PositiveIntegerField(default=0)),
                ("referrals_created", models.PositiveIntegerField(default=0)),
                ("one_to_ones_created", models.PositiveIntegerField(default=0)),
                ("tyfcbs_created", models.PositiveIntegerField(default=0)),
                ("errors_count", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_details", models.JSONField(blank=True, default=list)),
                (
                    "chapter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chapters.chapter",
                    ),
                ),
                (
                    "imported_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-import_date"],
            },
        ),
        migrations.CreateModel(
            name="Referral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_given", models.DateField(auto_now_add=True)),
                ("week_of", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "giver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_given",
                        to="chapters.member",
                    ),
                ),
                (
                    "receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="referrals_received",
                        to="chapters.member",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_given"],
                "unique_together": {("giver", "receiver", "date_given")},
            },
        ),
    ]
