# Generated by Django 4.2.7 on 2025-09-30 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bni', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataimportsession',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='dataimportsession',
            name='imported_by',
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='member',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='member',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='membermonthlystats',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='membermonthlystats',
            name='member',
        ),
        migrations.RemoveField(
            model_name='membermonthlystats',
            name='monthly_report',
        ),
        migrations.AlterUniqueTogether(
            name='monthlyreport',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='monthlyreport',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='onetoone',
            name='member1',
        ),
        migrations.RemoveField(
            model_name='onetoone',
            name='member2',
        ),
        migrations.AlterUniqueTogether(
            name='referral',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='referral',
            name='giver',
        ),
        migrations.RemoveField(
            model_name='referral',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='tyfcb',
            name='giver',
        ),
        migrations.RemoveField(
            model_name='tyfcb',
            name='receiver',
        ),
        migrations.DeleteModel(
            name='Chapter',
        ),
        migrations.DeleteModel(
            name='DataImportSession',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='MemberMonthlyStats',
        ),
        migrations.DeleteModel(
            name='MonthlyReport',
        ),
        migrations.DeleteModel(
            name='OneToOne',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='TYFCB',
        ),
    ]
